import { Product } from './types';

export const products: Product[] = [
  // --- FOOTBALL ---
  {
    id: '1',
    name: 'Giày Bóng Đá Nike Mercurial Vapor 15',
    slug: 'giay-bong-da-nike-mercurial-vapor-15',
    price: 3200000,
    originalPrice: 3500000,
    description: 'Giày bóng đá Nike Mercurial Vapor 15 Elite FG là phiên bản cao cấp nhất, mang lại cảm giác bóng chân thực và tốc độ tối đa.',
    category: 'Bóng đá',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800'],
    sizes: ['39', '40', '41', '42', '43'],
    colors: ['Đỏ', 'Xanh'],
    stock: 15,
    rating: 4.8,
    numReviews: 124,
    isFeatured: true,
    isNew: true,
  },
  {
    id: '2',
    name: 'Găng Tay Thủ Môn Adidas Predator Pro',
    slug: 'gang-tay-thu-mon-adidas-predator-pro',
    price: 1850000,
    description: 'Găng tay thủ môn chuyên nghiệp với công nghệ Demonpax 2.0 giúp kiểm soát bóng tốt nhất.',
    category: 'Bóng đá',
    brand: 'Adidas',
    images: ['https://media.soccerstore.vn/soccerstore/2024/10/1486812350-Gang-tay-thu-mon-adidas-Predator-Pro-Manuel-Neuer.jpg'],
    sizes: ['8', '9', '10'],
    colors: ['Trắng/Hồng', 'Đen'],
    stock: 8,
    rating: 4.9,
    numReviews: 56,
  },
  {
    id: '3',
    name: 'Quả Bóng Đá FIFA World Cup 2022 Al Rihla',
    slug: 'qua-bong-da-world-cup-2022',
    price: 3500000,
    description: 'Bóng thi đấu chính thức World Cup 2022 với công nghệ Speedshell ổn định quỹ đạo bay.',
    category: 'Bóng đá',
    brand: 'Adidas',
    images: ['https://cdn-images.vtv.vn/2022/3/31/photo-1-16487310064491116958818.jpg'],
    sizes: ['Size 5'],
    colors: ['Đa sắc'],
    stock: 25,
    rating: 5.0,
    numReviews: 310,
    isBestSeller: true,
  },
  {
    id: '4',
    name: 'Giày Bóng Đá Puma Future Ultimate',
    slug: 'giay-bong-da-puma-future-ultimate',
    price: 2900000,
    description: 'Giày bóng đá sáng tạo với công nghệ Fuzionfit360 ôm sát bàn chân, tối ưu sự linh hoạt.',
    category: 'Bóng đá',
    brand: 'Puma',
    images: ['https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&q=80&w=800'],
    sizes: ['40', '41', '42', '43'],
    colors: ['Xanh/Cam'],
    stock: 12,
    rating: 4.7,
    numReviews: 45,
  },
  {
    id: '5',
    name: 'Áo Đấu Đội Tuyển Việt Nam 2024',
    slug: 'ao-dau-tuyen-viet-nam-2024',
    price: 890000,
    description: 'Áo thi đấu chính thức của ĐTQG Việt Nam với chất liệu Interlock siêu bền và thoáng khí.',
    category: 'Bóng đá',
    brand: 'Grand Sport',
    images: ['https://media.vov.vn/sites/default/files/styles/large/public/2024-01/vietnam-new.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đỏ'],
    stock: 100,
    rating: 4.9,
    numReviews: 1200,
  },
  
  // --- RUNNING ---
  {
    id: '6',
    name: 'Giày Chạy Bộ Nike Air Zoom Pegasus 40',
    slug: 'nike-air-zoom-pegasus-40',
    price: 2800000,
    originalPrice: 3200000,
    description: 'Dòng giày chạy bộ huyền thoại của Nike, mang lại sự êm ái và phản hồi lực tốt cho mọi cự ly.',
    category: 'Chạy bộ',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&q=80&w=800'],
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['Xanh Dương', 'Đen', 'Xám'],
    stock: 30,
    rating: 4.7,
    numReviews: 450,
    isFeatured: true,
  },
  {
    id: '7',
    name: 'Giày Asics Gel-Kayano 30 Premium',
    slug: 'asics-gel-kayano-30',
    price: 4500000,
    description: 'Độ ổn định tối đa cho người chạy có bàn chân bẹt, công nghệ 4D Guidance System tiên tiến.',
    category: 'Chạy bộ',
    brand: 'Asics',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800'],
    sizes: ['40', '41', '42', '43'],
    colors: ['Xanh Navy'],
    stock: 15,
    rating: 4.9,
    numReviews: 180,
  },
  {
    id: '8',
    name: 'Đồng Hồ Garmin Forerunner 255',
    slug: 'garmin-forerunner-255',
    price: 8500000,
    description: 'Đồng hồ GPS chuyên dụng cho chạy bộ, theo dõi chỉ số sức khỏe và hiệu suất tập luyện chi tiết.',
    category: 'Phụ kiện',
    brand: 'Garmin',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800'],
    sizes: ['One Size'],
    colors: ['Đen', 'Xám'],
    stock: 10,
    rating: 4.8,
    numReviews: 95,
  },
  {
    id: '9',
    name: 'Áo Chạy Bộ Nike Dri-FIT ADV',
    slug: 'ao-chay-bo-nike-dri-fit-adv',
    price: 1200000,
    description: 'Chất liệu vải cao cấp từ Nike, thấm hút mồ hôi cực nhanh giúp bạn luôn khô thoáng.',
    category: 'Chạy bộ',
    brand: 'Nike',
    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXBfhhXDuqaOYU0nmGGEtwdDxQoSaKmFjl-A&s'],
    sizes: ['S', 'M', 'L'],
    colors: ['Xanh Neon', 'Cam'],
    stock: 45,
    rating: 4.6,
    numReviews: 67,
  },
  {
    id: '10',
    name: 'Giày Running Hoka Clifton 9',
    slug: 'hoka-clifton-9',
    price: 3600000,
    description: 'Trọng lượng siêu nhẹ với lớp đệm dày, mang lại cảm giác lướt đi trên mây.',
    category: 'Chạy bộ',
    brand: 'Hoka',
    images: ['https://images.unsplash.com/photo-1605348532760-6753d2c43329?auto=format&fit=crop&q=80&w=800'],
    sizes: ['41', '42', '43', '44'],
    colors: ['Xanh Chuối'],
    stock: 20,
    rating: 4.9,
    numReviews: 140,
    isNew: true,
  },

  // --- BASKETBALL ---
  {
    id: '11',
    name: 'Giày Bóng Rổ Nike LeBron 20',
    slug: 'nike-lebron-20',
    price: 5200000,
    description: 'Thiết kế mới nhẹ hơn, nhanh hơn hỗ trợ các bước nhảy và di chuyển linh hoạt trên sân.',
    category: 'Bóng rổ',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    colors: ['Violet', 'Đen'],
    stock: 12,
    rating: 4.8,
    numReviews: 230,
    isFeatured: true,
  },
  {
    id: '12',
    name: 'Quả Bóng Rổ Wilson NBA Official',
    slug: 'wilson-nba-official-ball',
    price: 4200000,
    description: 'Bóng da thật dùng cho thi đấu chuyên nghiệp tại NBA.',
    category: 'Bóng rổ',
    brand: 'Wilson',
    images: ['https://file.hstatic.net/200000636469/file/bong-ro-wilson-nba-size-7__5__grande.jpg'],
    sizes: ['Size 7'],
    colors: ['Cam'],
    stock: 5,
    rating: 5.0,
    numReviews: 45,
  },
  {
    id: '13',
    name: 'Áo Bóng Rổ Golden State Warriors Curry',
    slug: 'ao-bong-ro-warriors-curry',
    price: 2200000,
    description: 'Phiên bản Swingman từ Nike, vải lưới thoáng khí và logo NBA thêu sắc nét.',
    category: 'Bóng rổ',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1515523110800-9415d13b84a8?auto=format&fit=crop&q=80&w=800'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Xanh/Vàng'],
    stock: 30,
    rating: 4.9,
    numReviews: 88,
  },
  {
    id: '14',
    name: 'Giày Bóng Rổ Adidas Harden Vol 7',
    slug: 'adidas-harden-vol-7',
    price: 4200000,
    description: 'Đệm Lightstrike siêu phản hồi và thiết kế tương lai độc đáo.',
    category: 'Bóng rổ',
    brand: 'Adidas',
    images: ['https://images.unsplash.com/photo-1579338559194-a162d19bf842?auto=format&fit=crop&q=80&w=800'],
    sizes: ['42', '43', '44'],
    colors: ['Bạc', 'Đỏ'],
    stock: 10,
    rating: 4.7,
    numReviews: 43,
  },

  // --- GYM & TRAINING ---
  {
    id: '15',
    name: 'Giày Tập Luyện Nike Metcon 9',
    slug: 'nike-metcon-9',
    price: 3800000,
    description: 'Chuyên dụng cho CrossFit và nâng tạ với đế phẳng cực kỳ ổn định.',
    category: 'Gym',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=800'],
    sizes: ['40', '41', '42', '43'],
    colors: ['Trắng', 'Đen'],
    stock: 22,
    rating: 4.9,
    numReviews: 120,
    isBestSeller: true,
  },
  {
    id: '16',
    name: 'Dây Kháng Lực Đa Năng TRX Home2',
    slug: 'trx-home2-system',
    price: 4900000,
    description: 'Hệ thống tập luyện toàn thân bằng trọng lượng cơ thể tại nhà.',
    category: 'Phụ kiện',
    brand: 'TRX',
    images: ['https://product.hstatic.net/1000185761/product/multi-way-expander_1d487f7ab077449aab6fa788144ef2c6_grande.jpg'],
    sizes: ['Adjustable'],
    colors: ['Vàng/Đen'],
    stock: 15,
    rating: 4.8,
    numReviews: 34,
  },
  {
    id: '17',
    name: 'Tạ Tay Gang Cao Cấp 10kg',
    slug: 'ta-tay-gang-10kg',
    price: 650000,
    description: 'Tạ tay đúc nguyên khối, bọc cao su chống va đập và giảm tiếng ồn.',
    category: 'Gym',
    brand: 'C&T Sport',
    images: ['https://images.unsplash.com/photo-1586401100295-7a8096fd231a?auto=format&fit=crop&q=80&w=800'],
    sizes: ['10kg', '15kg', '20kg'],
    colors: ['Đen'],
    stock: 40,
    rating: 4.5,
    numReviews: 210,
  },
  {
    id: '18',
    name: 'Thảm Tập Yoga Lululemon 5mm Reversible',
    slug: 'tham-yoga-lululemon-5mm',
    price: 2500000,
    description: 'Thảm tập yoga chất lượng cao nhất thị trường với độ bám cực tốt kể cả khi ướt.',
    category: 'Yoga',
    brand: 'Lululemon',
    images: ['https://yogaismylife.vn/wp-content/uploads/2024/07/Lululemon-The-Reversible-Mat-5mm-jpg.webp'],
    sizes: ['Standard'],
    colors: ['Xanh Mint', 'Tím', 'Hồng'],
    stock: 25,
    rating: 4.9,
    numReviews: 156,
  },
  {
    id: '19',
    name: 'Súng Massage Cơ Theragun PRO 5th Gen',
    slug: 'theragun-pro-5th-gen',
    price: 15900000,
    description: 'Thiết bị giải cơ chuyên sâu cho vận động viên chuyên nghiệp.',
    category: 'Phụ kiện',
    brand: 'Therabody',
    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZFuxmxmm4bPJMHCRoU9u0WXhOVmfsLSK-Hg&s'],
    sizes: ['Pro'],
    colors: ['Đen'],
    stock: 5,
    rating: 4.9,
    numReviews: 22,
  },
  {
    id: '20',
    name: 'Quần Short Tập Luyện Adidas Ergo',
    slug: 'quan-short-adidas-ergo',
    price: 950000,
    description: 'Quần short siêu nhẹ với công nghệ Aeroready giúp kiểm soát độ ẩm.',
    category: 'Gym',
    brand: 'Adidas',
    images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&q=80&w=800'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xám'],
    stock: 60,
    rating: 4.6,
    numReviews: 48,
  },

  // --- TENNIS & BADMINTON ---
  {
    id: '21',
    name: 'Vợt Tennis Wilson Pro Staff v14',
    slug: 'wilson-pro-staff-v14',
    price: 6800000,
    description: 'Dòng vợt huyền thoại được ưa chuộng bởi Roger Federer, mang lại sự kiểm soát tuyệt đối.',
    category: 'Tennis',
    brand: 'Wilson',
    images: ['https://imageio.forbes.com/specials-images/imageserve/63ef9fe92ae6752406b8d5ae/Wilson-Pro-Staff-v14/0x0.jpg?height=474&width=480&fit=bounds'],
    sizes: ['L2', 'L3'],
    colors: ['Đồng/Đen'],
    stock: 8,
    rating: 4.9,
    numReviews: 32,
    isFeatured: true,
  },
  {
    id: '22',
    name: 'Vợt Cầu Lông Yonex Astrox 99 Pro',
    slug: 'yonex-astrox-99-pro',
    price: 4500000,
    description: 'Vợt tấn công mạnh mẽ với công nghệ Namd cho cú đập cháy sân.',
    category: 'Cầu lông',
    brand: 'Yonex',
    images: ['https://ducansport.vn/images/products/2022/09/08/2-382.jpg'],
    sizes: ['3U', '4U'],
    colors: ['White Tiger', 'Cherry Sunburst'],
    stock: 15,
    rating: 4.8,
    numReviews: 120,
  },
  {
    id: '23',
    name: 'Giày Tennis Nike Court Air Zoom Vapor 11',
    slug: 'nike-court-vapor-11',
    price: 4200000,
    description: 'Uốn lượn sát mặt sân để tăng tốc độ di chuyển và độ bền tối đa.',
    category: 'Tennis',
    brand: 'Nike',
    images: ['https://sneakerdaily.vn/wp-content/uploads/2023/08/Giay-Tennis-Nike-Court-Air-Zoom-Vapor-11-DR6966-101-3.png'],
    sizes: ['40', '41', '42', '43'],
    colors: ['Trắng/Xanh'],
    stock: 12,
    rating: 4.7,
    numReviews: 41,
  },
  {
    id: '24',
    name: 'Bóng Tennis Penn Championship (Thùng 24 lon)',
    slug: 'bong-tennis-penn-case',
    price: 2400000,
    description: 'Bóng tennis tiêu chuẩn thi đấu, bền vững và ổn định.',
    category: 'Tennis',
    brand: 'Penn',
    images: ['https://images.unsplash.com/photo-1592709823125-a191f07a2a5e?auto=format&fit=crop&q=80&w=800'],
    sizes: ['Case'],
    colors: ['Vàng'],
    stock: 10,
    rating: 4.6,
    numReviews: 29,
  },

  // --- SWIMMING ---
  {
    id: '25',
    name: 'Kính Bơi Speedo Fastskin Hyper Elite',
    slug: 'kinh-boi-speedo-fastskin',
    price: 1800000,
    description: 'Kính bơi thi đấu đỉnh cao với thiết kế thủy động lực học.',
    category: 'Bơi lội',
    brand: 'Speedo',
    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD1Qg02GqvB5Ws6OIHfetICT_Z9vSIq6S-_Q&s'],
    sizes: ['One Size'],
    colors: ['Mirror Gold', 'Black Smoke'],
    stock: 20,
    rating: 4.9,
    numReviews: 54,
  },
  {
    id: '26',
    name: 'Quần Bơi Adidas Solid Swim Trunks',
    slug: 'quan-boi-adidas-solid',
    price: 850000,
    description: 'Chất liệu vải Infinitex Fitness Eco chống Clo bền bỉ.',
    category: 'Bơi lội',
    brand: 'Adidas',
    images: ['https://cdn.vuahanghieu.com/unsafe/0x900/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2023/02/quan-shorts-adidas-adicolor-classics-3-stripes-swim-shorts-hf2118-mau-cam-size-xs-63f02eeebee7a-18022023085038.jpg'],
    sizes: ['S', 'M', 'L'],
    colors: ['Xanh Navy', 'Đen'],
    stock: 35,
    rating: 4.4,
    numReviews: 38,
  },

  // --- ADDING MORE TO REACH >50 ---
  { 
    id: '27', 
    name: 'Túi Thể Thao Nike Brasilia 9.5', 
    price: 1200000, 
    category: 'Phụ kiện', 
    brand: 'Nike', 
    slug: 'nike-brasilia-95', 
    sizes: ['M'], 
    colors: ['Đen'], 
    stock: 50, 
    rating: 4.8, 
    numReviews: 210, 
    description: 'Túi trống thể thao Nike Brasilia giúp bạn sắp xếp tất cả các đồ dùng tập luyện một cách gọn gàng.',
    images: ['https://images.unsplash.com/photo-1547949003-9792a18a2601?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '28', 
    name: 'Bình Nước Thể Thao Hydro Flask 32oz', 
    price: 950000, 
    category: 'Phụ kiện', 
    brand: 'Hydro Flask', 
    slug: 'hydro-flask-32oz', 
    sizes: ['32oz'], 
    colors: ['Xanh', 'Hồng'], 
    stock: 30, 
    rating: 4.9, 
    numReviews: 890, 
    description: 'Bình nước cách nhiệt Hydro Flask giữ nước lạnh đến 24 giờ và nóng đến 12 giờ.',
    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGevdzsCW8HwxIQcTR_lhy9ga9WpHOHk88bA&s'] 
  },
  { 
    id: '29', 
    name: 'Tất Thể Thao Nike Everyday Cushion (3 Đôi)', 
    price: 450000, 
    category: 'Phụ kiện', 
    brand: 'Nike', 
    slug: 'tat-nike-everyday', 
    sizes: ['M', 'L'], 
    colors: ['Trắng', 'Đen'], 
    stock: 100, 
    rating: 4.7, 
    numReviews: 560, 
    description: 'Tất Nike Everyday với lớp đệm dày dưới lòng bàn chân giúp bạn thoải mái tối đa khi vận động.',
    images: ['https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '30', 
    name: 'Băng Đầu Gối Nike Pro Combat 2.0', 
    price: 650000, 
    category: 'Bóng rổ', 
    brand: 'Nike', 
    slug: 'bang-dau-goi-nike-pro', 
    sizes: ['M', 'L'], 
    colors: ['Đen'], 
    stock: 40, 
    rating: 4.6, 
    numReviews: 120, 
    description: 'Băng bảo vệ đầu gối hỗ trợ khớp gối khi vận động mạnh, giảm thiểu chấn thương.',
    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTho1MdzLVwzctdGCwpZ0UkyzHEuKKfqOEUUA&s'] 
  },
  { 
    id: '31', 
    name: 'Giày Outdoor Salomon Speedcross 6', 
    price: 3900000, 
    category: 'Chạy bộ', 
    brand: 'Salomon', 
    slug: 'salomon-speedcross-6', 
    sizes: ['41', '42'], 
    colors: ['Xanh Lá'], 
    stock: 15, 
    rating: 4.9, 
    numReviews: 76, 
    description: 'Giày chạy địa hình chuyên nghiệp với độ bám cực tốt trên bề mặt bùn đất và trơn trượt.',
    images: ['https://product.hstatic.net/200000931659/product/giay-chay-trail-running-nu-salomon-speedscross-6-gtx-l47466200__3__bdf536089d8144a690ff986fde5beec6.png'] 
  },
  { 
    id: '32', 
    name: 'Vợt Pickleball Selkirk Vanguard Power Air', 
    price: 5800000, 
    category: 'Pickleball', 
    brand: 'Selkirk', 
    slug: 'selkirk-pickleball-vanguard', 
    sizes: ['Epic'], 
    colors: ['Đỏ'], 
    stock: 4, 
    rating: 5.0, 
    numReviews: 12, 
    description: 'Vợt Pickleball cao cấp nhất từ Selkirk cho cảm giác bóng và sức mạnh vượt trội.',
    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSesTADecJ9qoirEdUo5firtKfozVypnaSUZw&s'] 
  },
  { 
    id: '33', 
    name: 'Xe Đạp Thể Thao Trek Marlin 7 Gen 3', 
    price: 22500000, 
    category: 'Đạp xe', 
    brand: 'Trek', 
    slug: 'trek-marlin-7-gen3', 
    sizes: ['M', 'L'], 
    colors: ['Xanh'], 
    stock: 3, 
    rating: 4.8, 
    numReviews: 25, 
    description: 'Xe đạp địa hình cao cấp Trek Marlin 7 với khung nhôm siêu nhẹ và giảm xóc RockShox.',
    images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '34', 
    name: 'Giày Đạp Xe Shimano RC7', 
    price: 4800000, 
    category: 'Đạp xe', 
    brand: 'Shimano', 
    slug: 'shimano-rc7-shoes', 
    sizes: ['41', '42'], 
    colors: ['Trắng'], 
    stock: 10, 
    rating: 4.7, 
    numReviews: 31, 
    description: 'Giày xe đạp đua chuyên dụng với đế carbon cứng cáp cho lực đạp tối ưu.',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '35', 
    name: 'Mũ Bảo Hiểm Đạp Xe Giro Aether Spherical', 
    price: 7200000, 
    category: 'Đạp xe', 
    brand: 'Giro', 
    slug: 'giro-aether-helmet', 
    sizes: ['M', 'L'], 
    colors: ['Matte Black'], 
    stock: 6, 
    rating: 4.9, 
    numReviews: 18, 
    description: 'Mũ bảo hiểm cao cấp tích hợp công nghệ MIPS Spherical bảo vệ não bộ tối ưu.',
    images: ['https://down-vn.img.susercontent.com/file/7407c907a32b4051025151b8f737987b'] 
  },
  { 
    id: '36', 
    name: 'Dây Nhảy Tốc Độ Rogue SR-1 Đạn Bạc', 
    price: 850000, 
    category: 'Gym', 
    brand: 'Rogue', 
    slug: 'rogue-sr1-speed-rope', 
    sizes: ['Adjustable'], 
    colors: ['Đỏ'], 
    stock: 25, 
    rating: 4.9, 
    numReviews: 145, 
    description: 'Dây nhảy tốc độ dùng trong thi đấu CrossFit với hệ thống ổ bi cực mượt.',
    images: ['https://assets.roguefitness.com/f_auto,q_auto,c_limit,w_1600,b_rgb:ffffff/catalog/Conditioning/Jump%20Ropes%20/SR%20Series/SR-1/AD0061-XX/AD0061-PURPLE-H_cfnfij.png'] 
  },
  { 
    id: '37', 
    name: 'Giày Tập Gym Reebok Nano X3', 
    price: 3200000, 
    category: 'Gym', 
    brand: 'Reebok', 
    slug: 'reebok-nano-x3', 
    sizes: ['40', '41', '42'], 
    colors: ['Xám'], 
    stock: 20, 
    rating: 4.8, 
    numReviews: 76, 
    description: 'Phát minh mới nhất từ dòng giày Nano, cân bằng giữa chạy bộ và nâng tạ.',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '38', 
    name: 'Găng Tay Boxing Hayabusa T3 12oz', 
    price: 4200000, 
    category: 'Võ thuật', 
    brand: 'Hayabusa', 
    slug: 'hayabusa-t3-gloves', 
    sizes: ['12oz', '14oz'], 
    colors: ['Đen/Trắng'], 
    stock: 5, 
    rating: 5.0, 
    numReviews: 88, 
    description: 'Găng tay boxing bảo vệ cổ tay tốt nhất thế giới với hệ thống khóa kép.',
    images: ['https://down-vn.img.susercontent.com/file/vn-11134207-820l4-mio989zoz1tzca'] 
  },
  { 
    id: '39', 
    name: 'Áo Khoác Gió Nike Windrunner', 
    price: 2900000, 
    category: 'Thời trang', 
    brand: 'Nike', 
    slug: 'nike-windrunner-jacket', 
    sizes: ['S', 'M', 'L'], 
    colors: ['Multicolor'], 
    stock: 15, 
    rating: 4.7, 
    numReviews: 234, 
    description: 'Chiếc áo khoác gió mang tính biểu tượng của Nike với thiết kế chevron 26 độ đặc trưng.',
    images: ['https://sneakerdaily.vn/wp-content/uploads/2024/07/Ao-Nike-Sportswear-Windrunner-Men-Hooded-Jacket-DA0002-018-1.jpg'] 
  },
  { 
    id: '40', 
    name: 'Túi Đeo Chéo Adidas Originals Fest', 
    price: 550000, 
    category: 'Phụ kiện', 
    brand: 'Adidas', 
    slug: 'adidas-fest-bag', 
    sizes: ['One Size'], 
    colors: ['Xanh Dương'], 
    stock: 40, 
    rating: 4.5, 
    numReviews: 112, 
    description: 'Túi đeo chéo nhỏ gọn đựng điện thoại và ví tiền phong cách đường phố.',
    images: ['https://images.unsplash.com/photo-1547949003-9792a18a2601?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '41', 
    name: 'Giày Sneaker Adidas Ultraboost Light', 
    price: 5000000, 
    category: 'Chạy bộ', 
    brand: 'Adidas', 
    slug: 'adidas-ultraboost-light', 
    sizes: ['39', '40', '41', '42'], 
    colors: ['Trắng'], 
    stock: 12, 
    rating: 4.9, 
    numReviews: 312, 
    description: 'Phiên bản Ultraboost nhẹ nhất lịch sử, mang lại năng lượng hoàn hảo cho đôi chân.',
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '42', 
    name: 'Áo Polo Tennis Lacoste Novak Djokovic', 
    price: 3500000, 
    category: 'Tennis', 
    brand: 'Lacoste', 
    slug: 'lacoste-djokovic-polo', 
    sizes: ['M', 'L'], 
    colors: ['Xanh Lá'], 
    stock: 20, 
    rating: 4.8, 
    numReviews: 56, 
    description: 'Áo Polo thi đấu chính thức của Novak Djokovic, sang trọng và thoáng khí.',
    images: ['https://product.hstatic.net/200000870593/product/dh7360_iiu_24_092cc53a79e74943a84f80b7fe9b82ae_1024x1024.jpg'] 
  },
  { 
    id: '43', 
    name: 'Gậy Golf Driver TaylorMade Stealth 2', 
    price: 15500000, 
    category: 'Golf', 
    brand: 'TaylorMade', 
    slug: 'taylormade-stealth2-driver', 
    sizes: ['9.0', '10.5'], 
    colors: ['Đen/Đỏ'], 
    stock: 3, 
    rating: 4.9, 
    numReviews: 24, 
    description: 'Gậy driver carbon tối ưu tốc độ bóng và độ ổn định khi đánh lệch tâm.',
    images: ['https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '44', 
    name: 'Túi Golf Sunday Carry Bag', 
    price: 2800000, 
    category: 'Golf', 
    brand: 'Titleist', 
    slug: 'titleist-sunday-bag', 
    sizes: ['M'], 
    colors: ['Ghi'], 
    stock: 5, 
    rating: 4.7, 
    numReviews: 14, 
    description: 'Túi golf cầm tay nhỏ gọn cho những buổi tập cuối tuần nhanh chóng.',
    images: ['https://images.unsplash.com/photo-1547949003-9792a18a2601?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '45', 
    name: 'Găng Tay Golf FootJoy StaSof', 
    price: 650000, 
    category: 'Golf', 
    brand: 'FootJoy', 
    slug: 'footjoy-stasof-glove', 
    sizes: ['S', 'M', 'L'], 
    colors: ['Trắng'], 
    stock: 50, 
    rating: 4.9, 
    numReviews: 215, 
    description: 'Găng tay golf bằng da cừu số 1 thế giới được các Pro tin dùng.',
    images: ['https://product.hstatic.net/1000007560/product/gang_tay_golf_stasof_fj_66778_footjoy_66880be284bf4b769ea0651aee9694c5_large.jpg'] 
  },
  { 
    id: '46', 
    name: 'Ván Trượt Element Complete Skateboard', 
    price: 2200000, 
    category: 'Skateboard', 
    brand: 'Element', 
    slug: 'element-skateboard-complete', 
    sizes: ['8.0'], 
    colors: ['Đa sắc'], 
    stock: 10, 
    rating: 4.7, 
    numReviews: 56, 
    description: 'Bộ ván trượt Element hoàn chỉnh phù hợp cho cả người mới và dân chuyên nghiệp.',
    images: ['https://skateboardvietnam.com/wp-content/uploads/2020/09/Element-Skateboard-vietnam-4.jpg'] 
  },
  { 
    id: '47', 
    name: 'Mũ Lưỡi Trai Nike Heritage 86', 
    price: 650000, 
    category: 'Phụ kiện', 
    brand: 'Nike', 
    slug: 'nike-h86-cap', 
    sizes: ['One Size'], 
    colors: ['Đen', 'Trắng', 'Ghi'], 
    stock: 100, 
    rating: 4.6, 
    numReviews: 345, 
    description: 'Mũ lưỡi trai Nike phong cách cổ điển, chất liệu vải thô bền đẹp.',
    images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800'] 
  },
  { 
    id: '48', 
    name: 'Băng Trán Thấm Mồ Hôi Jordan Jumpman', 
    price: 350000, 
    category: 'Bóng rổ', 
    brand: 'Jordan', 
    slug: 'jordan-headband', 
    sizes: ['One Size'], 
    colors: ['Đỏ', 'Đen'], 
    stock: 80, 
    rating: 4.8, 
    numReviews: 120, 
    description: 'Băng trán Jordan Jumpman thấm hút mồ hôi cực tốt cho dân chơi bóng rổ.',
    images: ['https://lh6.googleusercontent.com/proxy/w_mkYsQliLmIp-fJFIUDy9s2lOgq5BLaLEOpTtpqM7vLFNUnAWlPId2RVGmTH0NYDjHVmgohFnJPBkafMcbKoHTHPf3mssKC-1-AR6TC7Tt13ZT9Un-gdRt1CaUIIAU4HQ147Ge9uyfH8K4Dk1-9kl-OhtoveZEJQA5zsu_p4spxfSvAcfQb7NxlvkU3pw'] 
  },
  { 
    id: '49', 
    name: 'Dây Quấn Cổ Tay Lifting Straps Rogue', 
    price: 450000, 
    category: 'Gym', 
    brand: 'Rogue', 
    slug: 'rogue-lifting-straps', 
    sizes: ['One Size'], 
    colors: ['Xám'], 
    stock: 60, 
    rating: 4.9, 
    numReviews: 95, 
    description: 'Dây kéo cổ tay chuyên dùng trong tập gym cường độ cao và nâng tạ nặng.',
    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP5vD9qH0mz3KvhpPC4koFRLtMnFS6ZTRVhg&s'] 
  },
  { 
    id: '50', 
    name: 'Xà Đơn Gắn Tửa Đa Năng C&T', 
    price: 850000, 
    category: 'Gym', 
    brand: 'C&T Sport', 
    slug: 'xa-don-gan-tua', 
    sizes: ['Adjustable'], 
    colors: ['Đen/Cam'], 
    stock: 30, 
    rating: 4.7, 
    numReviews: 178, 
    description: 'Xà đơn gắn cửa chịu lực cực tốt, lắp đặt đơn giản không cần khoan đục.',
    images: ['https://24hsport.vn/webroot/img/images/xa-don-gan-tuong-da-nang-8-in-1-2023-e.jpg'] 
  },
  { 
    id: '51', 
    name: 'Gương Tập Gym Di Động C&T', 
    price: 2500000, 
    category: 'Gym', 
    brand: 'C&T Sport', 
    slug: 'guong-tap-gym', 
    sizes: ['Full Body'], 
    colors: ['Trắng'], 
    stock: 5, 
    rating: 4.5, 
    numReviews: 12, 
    description: 'Gương theo dõi tư thế tập luyện có chân đế di động linh hoạt.',
    images: ['https://kinhdaiduong.com/wp-content/uploads/2026/12/guong-soi-phong-tap-di-dong-1.jpg'] 
  },
  { 
    id: '52', 
    name: 'Bộ Côn Nhị Khúc Gỗ Sồi Cao Cấp', 
    price: 450000, 
    category: 'Võ thuật', 
    brand: 'C&T Sport', 
    slug: 'con-nhi-khuc-go', 
    sizes: ['Tiêu chuẩn'], 
    colors: ['Nâu'], 
    stock: 20, 
    rating: 4.9, 
    numReviews: 45, 
    description: 'Côn nhị khúc gỗ sồi bền bỉ, khớp xoay inox mượt mà cho việc tập luyện võ thuật.',
    images: ['https://product.hstatic.net/200000717719/product/93104817891_c549b2656af340d1886888b42b538b03.jpg'] 
  },
];
